### ISSUE TITLE
Does this work with @google-cloud/firestore?

### ISSUE THREAD

**Issue by joemckie** [fiery-data/fiery-firebase-memory#1]
Love the idea behind this, just wondered whether it works with the newer version of Firestore, or only with Firebase?

**Comment by ClickerMonkey** [comment]
I actually never got it working with firebase, just firestore. However I haven't been following changes to firestore lately so it might not have the latest and greatest.

**Comment by joemckie** [comment]
Yeah it doesn't work with the firestore provided by `@google-cloud/firestore` as it's missing a few functions 😞

Might not be too difficult to add in. Are you accepting PRs?

**Comment by ClickerMonkey** [comment]
Definitely!
